### ISSUE TITLE
Allow users to make a custom template

### ISSUE THREAD

**Issue by shabad** [saadq/latexresu.me#10]
Let users create custom templates, and make those templates available to other users as well.

**Comment by saadq** [comment]
Something like this is probably out of the scope for this project as it would require the need to have a built in LaTeX editor as well as functionality for uploading all the files and assets needed for the template. 

Instead, I think it might be a good idea to allow people to open `Template Request` issues with a screenshot and LaTeX code needed for the template in which case I could implement that template into the app. 

Alternatively, I would also be happy if someone would want to try it themselves and send a pull request. All the code for the templates is located [here](https://github.com/saadq/latexresu.me/tree/master/app/server/src/generator/templates).
