### ISSUE TITLE
Add word doc option

### ISSUE THREAD

**Issue by fszcze** [saadq/latexresu.me#16]
A majority of resume scanning software does not recognize PDFs. You have greater odds of being contacted back if you use a Word doc format.

**Comment by saadq** [comment]
Hey @fszcze thanks for raising this issue. Unfortunately, using LaTeX only allows you to get a PDF or DVI output.  Converting from PDF to Word is beyond the scope of the project itself, however you may want to look into using other solutions like https://www.pdftoword.com/. Hope you understand.
