### ISSUE TITLE
Award Details copied twice into the final document

### ISSUE THREAD

**Issue by 2018sjain** [saadq/latexresu.me#18]
For example, if I put "asdf" in Award Details, it shows up as "asdfasdf" in the Preview Resume tab underneath the award.

**Comment by saadq** [comment]
Which template did this happen with?

**Comment by 2018sjain** [comment]
The first template. Here are some images showing the problem.
![image](https://cloud.githubusercontent.com/assets/17102303/26758017/49583b2a-489f-11e7-8fd0-1a0b35a96e6d.png)
![image](https://cloud.githubusercontent.com/assets/17102303/26758018/51d8dcf0-489f-11e7-9764-194f5abaa985.png)

**Comment by saadq** [comment]
Thanks for finding this issue! I'll push out a fix asap.
