### ISSUE TITLE
'S' in Skills should not be capitalized (Template 6)

### ISSUE THREAD

**Issue by jacobjinkelly** [saadq/latexresu.me#24]
'skills' should be all lowercase to match the rest of section headers. See image.
![screen shot 2017-06-09 at 9 36 42 pm](https://user-images.githubusercontent.com/16728917/26998957-cbe67b40-4d5b-11e7-817a-d7376f7a107f.png)

**Comment by saadq** [comment]
Thanks for finding this issue! Would you like to submit a pull request and fix the casing over [here](https://github.com/saadq/latexresu.me/blob/master/app/server/src/generator/templates/template6/index.js#L146)?
