### ISSUE TITLE
fix inconsistency in logo on home screen and the main app screen

### ISSUE THREAD

**Issue by saadq** [saadq/latexresu.me#33]
On the home screen the "M" looks like this:

<img width="370" alt="screen shot 2017-08-15 at 8 46 14 am" src="https://user-images.githubusercontent.com/5678694/29316504-4856682a-8196-11e7-9e0e-053a3127091f.png">

On the main generator screen, it looks like this:

<img width="276" alt="screen shot 2017-08-15 at 8 46 36 am" src="https://user-images.githubusercontent.com/5678694/29316520-5239f96a-8196-11e7-99b3-e9ac3a2dd104.png">

For some reason, the home screen has the logo with a `text-transform: uppercase;`. That style should probably be removed.

**Comment by bonebizz21** [comment]
Thanks

**Comment by saadq** [comment]
Fixed in #34, thanks @TsimpDim!
