### ISSUE TITLE
Allow user to choose the order of the sections

### ISSUE THREAD

**Issue by saadq** [saadq/latexresu.me#6]
Right now the order is:

1. Profile
2. Education
3. Experience
4. Skills
5. Projects
6. Awards

A lot of the LaTeX templates are dependent on having the profile section be at the top. However, it should be possible to allow 2 -> 6 to be reordered.

**Comment by AgrawalAman** [comment]
Also allow users to rename the sections, Add Sections

**Comment by saadq** [comment]
I can allow users to rename the sections, however allowing the user to add sections is probably beyond the scope of this project. A lot of the templates require specific LaTeX code for each section and allowing users to add a section would be very hard to manage. Would their section be a list view? Paragraph view? It's all dependent on the template so it would be hard to implement.
