### ISSUE TITLE
let user save their data

### ISSUE THREAD

**Issue by kmahar** [saadq/latexresu.me#8]
another suggestion - would love feature to save online what I've filled out so that I can come back to it later on and add new stuff using your interface. I imagine that this would especially be useful for people who don't know latex and don't want to edit the downloaded source themselves

**Comment by gautamkrishnar** [comment]
I think using browser's local storage is a better option than saving in the server. If you have resources, you can consider saving user data in the server. 😄

**Comment by saadq** [comment]
This is something I was planning on implementing. I'd rather not use up server resources, but I was thinking something along the lines of importing/exporting your current resume data as JSON. That way you won't have any local storage issues if you clear your data.

**Comment by AgrawalAman** [comment]
JSON format seems a great idea, would be easily editable for developers to add bullets, change stuff, etc manually as well.

**Comment by themotu** [comment]
Yaml or Toml might be easier if people want to edit/read it directly

**Comment by lovasoa** [comment]
###  [JSON Resume](https://jsonresume.org/)

> The open source initiative to create a JSON-based standard for resumes.

It would be great if it could import/export resumes in the [jsonresume](https://jsonresume.org/) format.

**Comment by enzokarate** [comment]
I further support json IO of stuff.

**Comment by tushgup** [comment]
Yes! I'm trying to make a change in my resume but I can't figure out how to convert it back to PDF now. :/

**Comment by saadq** [comment]
Hey all, I know this is insanely late, but the [new](https://github.com/saadq/latexresu.me/tree/new) branch saves your session as well as letting you import/export your resume as JSON (compatible with JSON resume). Looking forward to releasing this new version soon.

**Comment by saadq** [comment]
@kmahar I just added you as a contributor to the README, let me know if you'd rather not be on there. Thanks your contribution :)

**Comment by kmahar** [comment]
@saadq fine with me! thanks for implementing the feature!!! :)
